dist: bionic
language: rust
rust:
  - nightly

services:
  - docker


jobs:
  include:
    - stage: Build, Unit-Tests & Fuzz-Tests
      go: 1.12.x
      script:
        - cargo install cargo-fuzz
        - sudo apt-get update && \
          openssl \
          libssl-dev \
          pkg-config \
          libsqlite3-dev \
          git \
          cmake \
          zip \
          libc++-dev \
          libc++abi-dev \
          libprotobuf-dev \
          protobuf-compiler
        - chmod +x ./ci/fuzzit.sh
        - ./ci/fuzzit.sh 

    - stage: Fuzzit (Fuzzing)
      if: branch = master AND type IN (push)
      go: 1.12.x
      script:
        - cargo install cargo-fuzz
        - ./ci/fuzzit.sh fuzzing
