dist: bionic
language: rust
rust:
  - nightly

services:
  - docker


jobs:
  include:
    - stage: Build, Unit-Tests & Fuzz-Tests
      go: 1.12.x
      script:
        - cargo install cargo-fuzz
        - chmod +x ./ci/fuzzit.sh
        - ./ci/fuzzit.sh regression

    - stage: Fuzzit (Fuzzing)
      if: branch = master AND type IN (push)
      go: 1.12.x
      script:
        - cargo install cargo-fuzz
        - ./ci/fuzzit.sh fuzzing
