version: 2.1

defaults:
  rust_image: &rust_image quay.io/tarilabs/rust_tari-build-with-deps:nightly-2020-06-10

commands:
  regression:
    description: Run fuzz regression tests
    parameters:
      release:
        description: Set this to true to compile in release mode.
        type: boolean
        default: false
    steps:
      - run:
          name: Install cargo-fuzz
          command: cargo install cargo-fuzz
      - run:
          name: Checkout and Build code
          command: |
            mkdir fuzztari
            cd fuzztari
            git clone https://github.com/tari-project/tari
            git clone https://github.com/tari-project/tari_utilities
            git clone https://github.com/tari-project/tari-crypto
            git clone https://github.com/the-mog/tari-fuzzer
            cd tari-fuzzer
            cargo run build


jobs:
  test-tari-release:
    docker:
      - image: *rust_image
    resource_class: medium
    steps:
      - regression:
          release: true

workflows:
  version: 2
  workflow:
    jobs:
      - test-tari-release:
          filters:
            branches:
              ignore: gh-pages
